/* ========================================================
   data.js — Champion Database + Constants
   DDragon 16.4.1 (Patch 26.4)
   ======================================================== */

const ROLES = { TOP: 'TOP', JG: 'JG', MID: 'MID', BOT: 'BOT', SUP: 'SUP' };

let DDRAGON_VERSION = '16.4.1';
const DDRAGON_IMG = (id) => `https://ddragon.leagueoflegends.com/cdn/${DDRAGON_VERSION}/img/champion/${id}.png`;

/* Draft turn order: standard LoL 10-ban 10-pick
   BAN_PHASE_1:  B-R-B-R-B-R  (6 bans)
   PICK_PHASE_1: B-R-R-B-B-R  (6 picks)
   BAN_PHASE_2:  R-B-R-B      (4 bans)
   PICK_PHASE_2: R-B-B-R      (4 picks)  */
const DRAFT_ORDER = [
  // BAN_PHASE_1
  { phase: 'BAN1', side: 'blue', type: 'ban', index: 0 },
  { phase: 'BAN1', side: 'red', type: 'ban', index: 0 },
  { phase: 'BAN1', side: 'blue', type: 'ban', index: 1 },
  { phase: 'BAN1', side: 'red', type: 'ban', index: 1 },
  { phase: 'BAN1', side: 'blue', type: 'ban', index: 2 },
  { phase: 'BAN1', side: 'red', type: 'ban', index: 2 },
  // PICK_PHASE_1
  { phase: 'PICK1', side: 'blue', type: 'pick', index: 0 },
  { phase: 'PICK1', side: 'red', type: 'pick', index: 0 },
  { phase: 'PICK1', side: 'red', type: 'pick', index: 1 },
  { phase: 'PICK1', side: 'blue', type: 'pick', index: 1 },
  { phase: 'PICK1', side: 'blue', type: 'pick', index: 2 },
  { phase: 'PICK1', side: 'red', type: 'pick', index: 2 },
  // BAN_PHASE_2
  { phase: 'BAN2', side: 'red', type: 'ban', index: 3 },
  { phase: 'BAN2', side: 'blue', type: 'ban', index: 3 },
  { phase: 'BAN2', side: 'red', type: 'ban', index: 4 },
  { phase: 'BAN2', side: 'blue', type: 'ban', index: 4 },
  // PICK_PHASE_2
  { phase: 'PICK2', side: 'red', type: 'pick', index: 3 },
  { phase: 'PICK2', side: 'blue', type: 'pick', index: 3 },
  { phase: 'PICK2', side: 'blue', type: 'pick', index: 4 },
  { phase: 'PICK2', side: 'red', type: 'pick', index: 4 },
];

/* Damage type tag */
const DMG = { AP: 'AP', AD: 'AD', MIXED: 'MIXED' };

/* Tags for TeamGameValue 6-axis (0=low, 1=mid, 2=high) */
function tgv(engage, objective, lane, disengage, flex, execDiff) {
  return {
    engageClarity: engage, objectiveControl: objective, laneStability: lane,
    disengage: disengage, flexValue: flex, executionDifficulty: execDiff
  };
}

/*  Each champion: { id, name, roles[], dmg, tags{}, image }
    roles = possible lanes (flexible — any champion can go to any lane in pick)
    tags = TeamGameValue default tags  */
const CHAMPIONS = [
  { id: 'Aatrox', name: 'Aatrox', roles: ['TOP'], dmg: 'AD', tags: tgv(2, 1, 2, 1, 0, 1) },
  { id: 'Ahri', name: 'Ahri', roles: ['MID'], dmg: 'AP', tags: tgv(1, 0, 2, 1, 0, 1) },
  { id: 'Akali', name: 'Akali', roles: ['MID', 'TOP'], dmg: 'AP', tags: tgv(1, 0, 1, 1, 1, 2) },
  { id: 'Akshan', name: 'Akshan', roles: ['MID', 'TOP'], dmg: 'AD', tags: tgv(0, 0, 1, 1, 1, 2) },
  { id: 'Alistar', name: 'Alistar', roles: ['SUP'], dmg: 'AP', tags: tgv(2, 1, 1, 1, 0, 0) },
  { id: 'Ambessa', name: 'Ambessa', roles: ['TOP'], dmg: 'AD', tags: tgv(2, 1, 1, 0, 0, 2) },
  { id: 'Amumu', name: 'Amumu', roles: ['JG', 'SUP'], dmg: 'AP', tags: tgv(2, 2, 1, 0, 1, 0) },
  { id: 'Anivia', name: 'Anivia', roles: ['MID'], dmg: 'AP', tags: tgv(0, 2, 2, 2, 0, 2) },
  { id: 'Annie', name: 'Annie', roles: ['MID', 'SUP'], dmg: 'AP', tags: tgv(2, 0, 1, 0, 1, 0) },
  { id: 'Aphelios', name: 'Aphelios', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 1, 1, 0, 0, 2) },
  { id: 'Ashe', name: 'Ashe', roles: ['BOT', 'SUP'], dmg: 'AD', tags: tgv(1, 1, 2, 1, 1, 0) },
  { id: 'AurelionSol', name: 'Aurelion Sol', roles: ['MID'], dmg: 'AP', tags: tgv(0, 1, 1, 0, 0, 2) },
  { id: 'Aurora', name: 'Aurora', roles: ['MID', 'TOP'], dmg: 'AP', tags: tgv(1, 0, 1, 1, 1, 1) },
  { id: 'Azir', name: 'Azir', roles: ['MID'], dmg: 'AP', tags: tgv(1, 1, 1, 2, 0, 2) },
  { id: 'Bard', name: 'Bard', roles: ['SUP'], dmg: 'AP', tags: tgv(1, 1, 1, 1, 0, 2) },
  { id: 'Belveth', name: "Bel'Veth", roles: ['JG'], dmg: 'AD', tags: tgv(0, 2, 0, 0, 0, 2) },
  { id: 'Blitzcrank', name: 'Blitzcrank', roles: ['SUP'], dmg: 'AP', tags: tgv(2, 0, 1, 0, 0, 0) },
  { id: 'Brand', name: 'Brand', roles: ['SUP', 'MID'], dmg: 'AP', tags: tgv(0, 1, 1, 0, 1, 1) },
  { id: 'Braum', name: 'Braum', roles: ['SUP'], dmg: 'AD', tags: tgv(1, 1, 1, 2, 0, 0) },
  { id: 'Briar', name: 'Briar', roles: ['JG'], dmg: 'AD', tags: tgv(1, 1, 0, 0, 0, 1) },
  { id: 'Caitlyn', name: 'Caitlyn', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 1, 2, 1, 0, 1) },
  { id: 'Camille', name: 'Camille', roles: ['TOP'], dmg: 'AD', tags: tgv(2, 1, 1, 0, 0, 2) },
  { id: 'Cassiopeia', name: 'Cassiopeia', roles: ['MID', 'BOT'], dmg: 'AP', tags: tgv(0, 1, 1, 1, 1, 2) },
  { id: 'Chogath', name: "Cho'Gath", roles: ['TOP', 'MID'], dmg: 'AP', tags: tgv(1, 2, 2, 0, 1, 0) },
  { id: 'Corki', name: 'Corki', roles: ['MID'], dmg: 'MIXED', tags: tgv(0, 0, 1, 1, 0, 1) },
  { id: 'Darius', name: 'Darius', roles: ['TOP'], dmg: 'AD', tags: tgv(1, 1, 2, 0, 0, 0) },
  { id: 'Diana', name: 'Diana', roles: ['JG', 'MID'], dmg: 'AP', tags: tgv(2, 2, 1, 0, 1, 1) },
  { id: 'Draven', name: 'Draven', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 0, 1, 0, 0, 2) },
  { id: 'DrMundo', name: 'Dr. Mundo', roles: ['TOP', 'JG'], dmg: 'MIXED', tags: tgv(0, 1, 2, 0, 1, 0) },
  { id: 'Ekko', name: 'Ekko', roles: ['JG', 'MID'], dmg: 'AP', tags: tgv(1, 1, 1, 1, 1, 2) },
  { id: 'Elise', name: 'Elise', roles: ['JG'], dmg: 'AP', tags: tgv(1, 1, 0, 0, 0, 2) },
  { id: 'Evelynn', name: 'Evelynn', roles: ['JG'], dmg: 'AP', tags: tgv(0, 0, 0, 0, 0, 2) },
  { id: 'Ezreal', name: 'Ezreal', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 0, 2, 1, 0, 2) },
  { id: 'Fiddlesticks', name: 'Fiddlesticks', roles: ['JG'], dmg: 'AP', tags: tgv(2, 1, 0, 0, 0, 2) },
  { id: 'Fiora', name: 'Fiora', roles: ['TOP'], dmg: 'AD', tags: tgv(0, 0, 1, 0, 0, 2) },
  { id: 'Fizz', name: 'Fizz', roles: ['MID'], dmg: 'AP', tags: tgv(1, 0, 0, 1, 0, 2) },
  { id: 'Galio', name: 'Galio', roles: ['MID', 'SUP'], dmg: 'AP', tags: tgv(2, 1, 2, 0, 1, 0) },
  { id: 'Gangplank', name: 'Gangplank', roles: ['TOP', 'MID'], dmg: 'MIXED', tags: tgv(0, 1, 1, 0, 1, 2) },
  { id: 'Garen', name: 'Garen', roles: ['TOP'], dmg: 'AD', tags: tgv(0, 0, 2, 0, 0, 0) },
  { id: 'Gnar', name: 'Gnar', roles: ['TOP'], dmg: 'MIXED', tags: tgv(2, 1, 1, 1, 0, 1) },
  { id: 'Gragas', name: 'Gragas', roles: ['JG', 'TOP', 'MID'], dmg: 'AP', tags: tgv(1, 1, 2, 2, 2, 1) },
  { id: 'Graves', name: 'Graves', roles: ['JG', 'TOP'], dmg: 'AD', tags: tgv(0, 1, 1, 0, 1, 1) },
  { id: 'Gwen', name: 'Gwen', roles: ['TOP'], dmg: 'AP', tags: tgv(0, 1, 1, 0, 0, 2) },
  { id: 'Hecarim', name: 'Hecarim', roles: ['JG'], dmg: 'AD', tags: tgv(2, 1, 0, 0, 0, 1) },
  { id: 'Heimerdinger', name: 'Heimerdinger', roles: ['MID', 'TOP', 'BOT'], dmg: 'AP', tags: tgv(0, 2, 2, 0, 1, 1) },
  { id: 'Hwei', name: 'Hwei', roles: ['MID', 'SUP'], dmg: 'AP', tags: tgv(1, 1, 1, 1, 1, 2) },
  { id: 'Illaoi', name: 'Illaoi', roles: ['TOP'], dmg: 'AD', tags: tgv(0, 1, 2, 0, 0, 1) },
  { id: 'Irelia', name: 'Irelia', roles: ['TOP', 'MID'], dmg: 'AD', tags: tgv(1, 1, 1, 0, 1, 2) },
  { id: 'Ivern', name: 'Ivern', roles: ['JG'], dmg: 'AP', tags: tgv(0, 2, 0, 2, 0, 1) },
  { id: 'Janna', name: 'Janna', roles: ['SUP'], dmg: 'AP', tags: tgv(0, 0, 1, 2, 0, 0) },
  { id: 'JarvanIV', name: 'Jarvan IV', roles: ['JG', 'TOP'], dmg: 'AD', tags: tgv(2, 2, 1, 0, 1, 0) },
  { id: 'Jax', name: 'Jax', roles: ['TOP', 'JG'], dmg: 'MIXED', tags: tgv(1, 1, 1, 0, 1, 1) },
  { id: 'Jayce', name: 'Jayce', roles: ['TOP', 'MID'], dmg: 'AD', tags: tgv(0, 0, 1, 1, 1, 2) },
  { id: 'Jhin', name: 'Jhin', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 1, 2, 0, 0, 1) },
  { id: 'Jinx', name: 'Jinx', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 2, 1, 0, 0, 1) },
  { id: 'Kaisa', name: "Kai'Sa", roles: ['BOT'], dmg: 'MIXED', tags: tgv(1, 1, 1, 1, 0, 2) },
  { id: 'Kalista', name: 'Kalista', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 2, 1, 0, 0, 2) },
  { id: 'Karma', name: 'Karma', roles: ['SUP', 'MID'], dmg: 'AP', tags: tgv(0, 0, 2, 1, 1, 0) },
  { id: 'Karthus', name: 'Karthus', roles: ['JG', 'MID'], dmg: 'AP', tags: tgv(0, 1, 0, 0, 1, 1) },
  { id: 'Kassadin', name: 'Kassadin', roles: ['MID'], dmg: 'AP', tags: tgv(1, 0, 0, 1, 0, 2) },
  { id: 'Katarina', name: 'Katarina', roles: ['MID'], dmg: 'AP', tags: tgv(1, 0, 0, 0, 0, 2) },
  { id: 'Kayle', name: 'Kayle', roles: ['TOP', 'MID'], dmg: 'MIXED', tags: tgv(0, 0, 0, 0, 1, 1) },
  { id: 'Kayn', name: 'Kayn', roles: ['JG'], dmg: 'AD', tags: tgv(1, 1, 0, 0, 0, 1) },
  { id: 'Kennen', name: 'Kennen', roles: ['TOP'], dmg: 'AP', tags: tgv(2, 1, 1, 0, 0, 1) },
  { id: 'Khazix', name: "Kha'Zix", roles: ['JG'], dmg: 'AD', tags: tgv(0, 0, 0, 0, 0, 2) },
  { id: 'Kindred', name: 'Kindred', roles: ['JG'], dmg: 'AD', tags: tgv(0, 2, 0, 1, 0, 2) },
  { id: 'Kled', name: 'Kled', roles: ['TOP'], dmg: 'AD', tags: tgv(2, 1, 1, 0, 0, 1) },
  { id: 'KogMaw', name: "Kog'Maw", roles: ['BOT'], dmg: 'MIXED', tags: tgv(0, 2, 1, 0, 0, 1) },
  { id: 'KSante', name: "K'Sante", roles: ['TOP'], dmg: 'AD', tags: tgv(2, 1, 2, 1, 0, 2) },
  { id: 'Leblanc', name: 'LeBlanc', roles: ['MID'], dmg: 'AP', tags: tgv(0, 0, 1, 1, 0, 2) },
  { id: 'LeeSin', name: 'Lee Sin', roles: ['JG', 'TOP'], dmg: 'AD', tags: tgv(2, 1, 1, 1, 1, 2) },
  { id: 'Leona', name: 'Leona', roles: ['SUP'], dmg: 'AP', tags: tgv(2, 1, 1, 0, 0, 0) },
  { id: 'Lillia', name: 'Lillia', roles: ['JG', 'TOP'], dmg: 'AP', tags: tgv(1, 1, 0, 0, 1, 1) },
  { id: 'Lissandra', name: 'Lissandra', roles: ['MID'], dmg: 'AP', tags: tgv(2, 1, 2, 1, 0, 1) },
  { id: 'Lucian', name: 'Lucian', roles: ['BOT', 'MID'], dmg: 'AD', tags: tgv(0, 0, 1, 0, 1, 1) },
  { id: 'Lulu', name: 'Lulu', roles: ['SUP'], dmg: 'AP', tags: tgv(0, 0, 1, 2, 0, 0) },
  { id: 'Lux', name: 'Lux', roles: ['SUP', 'MID'], dmg: 'AP', tags: tgv(0, 1, 2, 0, 1, 1) },
  { id: 'Malphite', name: 'Malphite', roles: ['TOP', 'SUP'], dmg: 'MIXED', tags: tgv(2, 1, 2, 0, 1, 0) },
  { id: 'Malzahar', name: 'Malzahar', roles: ['MID'], dmg: 'AP', tags: tgv(1, 2, 2, 0, 0, 0) },
  { id: 'Maokai', name: 'Maokai', roles: ['SUP', 'JG', 'TOP'], dmg: 'AP', tags: tgv(2, 2, 2, 0, 2, 0) },
  { id: 'MasterYi', name: 'Master Yi', roles: ['JG'], dmg: 'AD', tags: tgv(0, 2, 0, 0, 0, 1) },
  { id: 'Mel', name: 'Mel', roles: ['MID', 'SUP'], dmg: 'AP', tags: tgv(1, 1, 1, 1, 1, 1) },
  { id: 'Milio', name: 'Milio', roles: ['SUP'], dmg: 'AP', tags: tgv(0, 0, 1, 2, 0, 0) },
  { id: 'MissFortune', name: 'Miss Fortune', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 1, 2, 0, 0, 0) },
  { id: 'MonkeyKing', name: 'Wukong', roles: ['JG', 'TOP'], dmg: 'AD', tags: tgv(2, 1, 1, 0, 1, 0) },
  { id: 'Mordekaiser', name: 'Mordekaiser', roles: ['TOP'], dmg: 'AP', tags: tgv(1, 1, 2, 0, 0, 1) },
  { id: 'Morgana', name: 'Morgana', roles: ['SUP', 'MID'], dmg: 'AP', tags: tgv(0, 1, 2, 1, 1, 0) },
  { id: 'Naafiri', name: 'Naafiri', roles: ['MID', 'JG'], dmg: 'AD', tags: tgv(1, 0, 1, 0, 1, 0) },
  { id: 'Nami', name: 'Nami', roles: ['SUP'], dmg: 'AP', tags: tgv(1, 0, 2, 1, 0, 0) },
  { id: 'Nasus', name: 'Nasus', roles: ['TOP'], dmg: 'MIXED', tags: tgv(0, 1, 1, 0, 0, 0) },
  { id: 'Nautilus', name: 'Nautilus', roles: ['SUP'], dmg: 'AP', tags: tgv(2, 1, 1, 0, 0, 0) },
  { id: 'Neeko', name: 'Neeko', roles: ['MID', 'SUP', 'TOP'], dmg: 'AP', tags: tgv(2, 1, 1, 0, 2, 1) },
  { id: 'Nidalee', name: 'Nidalee', roles: ['JG'], dmg: 'AP', tags: tgv(0, 0, 0, 1, 0, 2) },
  { id: 'Nilah', name: 'Nilah', roles: ['BOT'], dmg: 'AD', tags: tgv(1, 1, 0, 0, 0, 2) },
  { id: 'Nocturne', name: 'Nocturne', roles: ['JG'], dmg: 'AD', tags: tgv(1, 1, 0, 0, 0, 1) },
  { id: 'Nunu', name: 'Nunu & Willump', roles: ['JG'], dmg: 'AP', tags: tgv(1, 2, 0, 0, 0, 0) },
  { id: 'Olaf', name: 'Olaf', roles: ['JG', 'TOP'], dmg: 'AD', tags: tgv(1, 1, 1, 0, 1, 0) },
  { id: 'Orianna', name: 'Orianna', roles: ['MID'], dmg: 'AP', tags: tgv(2, 1, 2, 1, 0, 1) },
  { id: 'Ornn', name: 'Ornn', roles: ['TOP'], dmg: 'MIXED', tags: tgv(2, 1, 2, 0, 0, 0) },
  { id: 'Pantheon', name: 'Pantheon', roles: ['TOP', 'MID', 'SUP'], dmg: 'AD', tags: tgv(2, 0, 1, 0, 2, 0) },
  { id: 'Poppy', name: 'Poppy', roles: ['JG', 'TOP', 'SUP'], dmg: 'AD', tags: tgv(1, 1, 2, 2, 2, 0) },
  { id: 'Pyke', name: 'Pyke', roles: ['SUP'], dmg: 'AD', tags: tgv(1, 0, 0, 0, 0, 2) },
  { id: 'Qiyana', name: 'Qiyana', roles: ['MID', 'JG'], dmg: 'AD', tags: tgv(1, 0, 0, 0, 1, 2) },
  { id: 'Quinn', name: 'Quinn', roles: ['TOP'], dmg: 'AD', tags: tgv(0, 0, 1, 1, 0, 1) },
  { id: 'Rakan', name: 'Rakan', roles: ['SUP'], dmg: 'AP', tags: tgv(2, 0, 0, 1, 0, 1) },
  { id: 'Rammus', name: 'Rammus', roles: ['JG'], dmg: 'MIXED', tags: tgv(1, 1, 0, 0, 0, 0) },
  { id: 'RekSai', name: "Rek'Sai", roles: ['JG'], dmg: 'AD', tags: tgv(1, 1, 0, 0, 0, 1) },
  { id: 'Rell', name: 'Rell', roles: ['SUP'], dmg: 'AP', tags: tgv(2, 1, 1, 0, 0, 0) },
  { id: 'Renata', name: 'Renata Glasc', roles: ['SUP'], dmg: 'AP', tags: tgv(0, 1, 1, 1, 0, 1) },
  { id: 'Renekton', name: 'Renekton', roles: ['TOP'], dmg: 'AD', tags: tgv(1, 0, 2, 0, 0, 0) },
  { id: 'Rengar', name: 'Rengar', roles: ['JG', 'TOP'], dmg: 'AD', tags: tgv(0, 0, 0, 0, 1, 2) },
  { id: 'Riven', name: 'Riven', roles: ['TOP'], dmg: 'AD', tags: tgv(1, 0, 1, 0, 0, 2) },
  { id: 'Rumble', name: 'Rumble', roles: ['TOP', 'MID'], dmg: 'AP', tags: tgv(0, 2, 1, 0, 1, 1) },
  { id: 'Ryze', name: 'Ryze', roles: ['MID', 'TOP'], dmg: 'AP', tags: tgv(0, 0, 2, 0, 1, 2) },
  { id: 'Samira', name: 'Samira', roles: ['BOT'], dmg: 'AD', tags: tgv(1, 0, 0, 0, 0, 2) },
  { id: 'Sejuani', name: 'Sejuani', roles: ['JG', 'TOP'], dmg: 'AP', tags: tgv(2, 2, 1, 0, 1, 0) },
  { id: 'Senna', name: 'Senna', roles: ['SUP', 'BOT'], dmg: 'AD', tags: tgv(0, 1, 2, 0, 1, 1) },
  { id: 'Seraphine', name: 'Seraphine', roles: ['SUP', 'MID', 'BOT'], dmg: 'AP', tags: tgv(1, 1, 2, 1, 2, 0) },
  { id: 'Sett', name: 'Sett', roles: ['TOP', 'SUP'], dmg: 'AD', tags: tgv(2, 1, 2, 0, 1, 0) },
  { id: 'Shaco', name: 'Shaco', roles: ['JG'], dmg: 'AD', tags: tgv(0, 0, 0, 0, 0, 2) },
  { id: 'Shen', name: 'Shen', roles: ['TOP', 'SUP'], dmg: 'MIXED', tags: tgv(1, 1, 2, 0, 1, 1) },
  { id: 'Shyvana', name: 'Shyvana', roles: ['JG'], dmg: 'MIXED', tags: tgv(0, 2, 0, 0, 0, 1) },
  { id: 'Singed', name: 'Singed', roles: ['TOP'], dmg: 'AP', tags: tgv(0, 0, 1, 0, 0, 1) },
  { id: 'Sion', name: 'Sion', roles: ['TOP'], dmg: 'AD', tags: tgv(2, 1, 2, 0, 0, 0) },
  { id: 'Sivir', name: 'Sivir', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 1, 2, 0, 0, 0) },
  { id: 'Skarner', name: 'Skarner', roles: ['JG', 'TOP'], dmg: 'MIXED', tags: tgv(2, 2, 1, 0, 1, 0) },
  { id: 'Smolder', name: 'Smolder', roles: ['BOT', 'MID'], dmg: 'AD', tags: tgv(0, 1, 2, 1, 1, 1) },
  { id: 'Sona', name: 'Sona', roles: ['SUP'], dmg: 'AP', tags: tgv(0, 0, 1, 1, 0, 0) },
  { id: 'Soraka', name: 'Soraka', roles: ['SUP'], dmg: 'AP', tags: tgv(0, 0, 2, 1, 0, 0) },
  { id: 'Swain', name: 'Swain', roles: ['SUP', 'MID', 'BOT'], dmg: 'AP', tags: tgv(1, 1, 2, 0, 2, 1) },
  { id: 'Sylas', name: 'Sylas', roles: ['MID', 'TOP'], dmg: 'AP', tags: tgv(1, 0, 1, 0, 1, 2) },
  { id: 'Syndra', name: 'Syndra', roles: ['MID'], dmg: 'AP', tags: tgv(0, 0, 2, 1, 0, 2) },
  { id: 'TahmKench', name: 'Tahm Kench', roles: ['TOP', 'SUP'], dmg: 'AP', tags: tgv(1, 1, 2, 0, 1, 0) },
  { id: 'Taliyah', name: 'Taliyah', roles: ['MID', 'JG'], dmg: 'AP', tags: tgv(1, 2, 1, 1, 1, 2) },
  { id: 'Talon', name: 'Talon', roles: ['MID', 'JG'], dmg: 'AD', tags: tgv(0, 0, 1, 0, 1, 1) },
  { id: 'Taric', name: 'Taric', roles: ['SUP'], dmg: 'AD', tags: tgv(1, 1, 1, 0, 0, 1) },
  { id: 'Teemo', name: 'Teemo', roles: ['TOP'], dmg: 'AP', tags: tgv(0, 1, 1, 0, 0, 1) },
  { id: 'Thresh', name: 'Thresh', roles: ['SUP'], dmg: 'AP', tags: tgv(2, 0, 1, 1, 0, 1) },
  { id: 'Tristana', name: 'Tristana', roles: ['BOT', 'MID'], dmg: 'AD', tags: tgv(0, 2, 1, 1, 1, 1) },
  { id: 'Trundle', name: 'Trundle', roles: ['JG', 'TOP'], dmg: 'AD', tags: tgv(0, 2, 1, 0, 1, 0) },
  { id: 'Tryndamere', name: 'Tryndamere', roles: ['TOP'], dmg: 'AD', tags: tgv(0, 1, 1, 0, 0, 1) },
  { id: 'TwistedFate', name: 'Twisted Fate', roles: ['MID'], dmg: 'MIXED', tags: tgv(0, 1, 2, 0, 0, 1) },
  { id: 'Twitch', name: 'Twitch', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 1, 0, 0, 0, 1) },
  { id: 'Udyr', name: 'Udyr', roles: ['JG', 'TOP'], dmg: 'MIXED', tags: tgv(1, 1, 1, 0, 1, 1) },
  { id: 'Urgot', name: 'Urgot', roles: ['TOP'], dmg: 'AD', tags: tgv(0, 1, 2, 0, 0, 1) },
  { id: 'Varus', name: 'Varus', roles: ['BOT', 'MID'], dmg: 'MIXED', tags: tgv(1, 1, 2, 0, 1, 1) },
  { id: 'Vayne', name: 'Vayne', roles: ['BOT', 'TOP'], dmg: 'AD', tags: tgv(0, 1, 0, 1, 1, 2) },
  { id: 'Veigar', name: 'Veigar', roles: ['MID', 'BOT'], dmg: 'AP', tags: tgv(1, 0, 1, 1, 1, 1) },
  { id: 'Velkoz', name: "Vel'Koz", roles: ['SUP', 'MID'], dmg: 'AP', tags: tgv(0, 2, 2, 0, 1, 1) },
  { id: 'Vex', name: 'Vex', roles: ['MID'], dmg: 'AP', tags: tgv(2, 0, 1, 0, 0, 1) },
  { id: 'Vi', name: 'Vi', roles: ['JG'], dmg: 'AD', tags: tgv(2, 1, 0, 0, 0, 0) },
  { id: 'Viego', name: 'Viego', roles: ['JG', 'TOP'], dmg: 'AD', tags: tgv(1, 1, 0, 0, 1, 2) },
  { id: 'Viktor', name: 'Viktor', roles: ['MID'], dmg: 'AP', tags: tgv(0, 1, 2, 1, 0, 2) },
  { id: 'Vladimir', name: 'Vladimir', roles: ['MID', 'TOP'], dmg: 'AP', tags: tgv(0, 0, 2, 1, 1, 1) },
  { id: 'Volibear', name: 'Volibear', roles: ['JG', 'TOP'], dmg: 'MIXED', tags: tgv(1, 2, 1, 0, 1, 0) },
  { id: 'Warwick', name: 'Warwick', roles: ['JG', 'TOP'], dmg: 'MIXED', tags: tgv(1, 1, 1, 0, 1, 0) },
  { id: 'Xayah', name: 'Xayah', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 1, 1, 1, 0, 1) },
  { id: 'Xerath', name: 'Xerath', roles: ['SUP', 'MID'], dmg: 'AP', tags: tgv(0, 1, 2, 0, 1, 1) },
  { id: 'XinZhao', name: 'Xin Zhao', roles: ['JG'], dmg: 'AD', tags: tgv(2, 1, 0, 0, 0, 0) },
  { id: 'Yasuo', name: 'Yasuo', roles: ['MID', 'TOP', 'BOT'], dmg: 'AD', tags: tgv(1, 0, 0, 0, 2, 2) },
  { id: 'Yone', name: 'Yone', roles: ['MID', 'TOP'], dmg: 'MIXED', tags: tgv(2, 0, 1, 0, 1, 2) },
  { id: 'Yorick', name: 'Yorick', roles: ['TOP'], dmg: 'AD', tags: tgv(0, 2, 2, 0, 0, 0) },
  { id: 'Yuumi', name: 'Yuumi', roles: ['SUP'], dmg: 'AP', tags: tgv(0, 0, 1, 0, 0, 0) },
  { id: 'Zac', name: 'Zac', roles: ['JG', 'TOP'], dmg: 'AP', tags: tgv(2, 1, 1, 0, 1, 0) },
  { id: 'Zed', name: 'Zed', roles: ['MID'], dmg: 'AD', tags: tgv(0, 0, 1, 1, 0, 2) },
  { id: 'Zeri', name: 'Zeri', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 1, 1, 1, 0, 2) },
  { id: 'Ziggs', name: 'Ziggs', roles: ['MID', 'BOT'], dmg: 'AP', tags: tgv(0, 2, 2, 0, 1, 1) },
  { id: 'Zilean', name: 'Zilean', roles: ['SUP', 'MID'], dmg: 'AP', tags: tgv(0, 0, 1, 1, 1, 1) },
  { id: 'Zoe', name: 'Zoe', roles: ['MID'], dmg: 'AP', tags: tgv(0, 0, 1, 0, 0, 2) },
  { id: 'Yunara', name: 'Yunara', roles: ['BOT'], dmg: 'AD', tags: tgv(0, 1, 1, 1, 0, 1) },
  { id: 'Zaahen', name: 'Zaahen', roles: ['JG', 'TOP'], dmg: 'AD', tags: tgv(1, 1, 1, 0, 1, 1) },
  { id: 'Zyra', name: 'Zyra', roles: ['SUP'], dmg: 'AP', tags: tgv(0, 2, 1, 1, 0, 1) },
];

// Add image URLs
CHAMPIONS.forEach(c => { c.image = DDRAGON_IMG(c.id); });

// Quick lookup map
const CHAMPION_MAP = {};
CHAMPIONS.forEach(c => { CHAMPION_MAP[c.id] = c; });

console.log(`data.js: ${CHAMPIONS.length} champions loaded`);
